FastGuard/Models/Ticket.cs
using System;
using System.Collections.Generic;

namespace FastGuard.Models
{
    public partial class Ticket
    {
        public int InvoiceId { get; set; }
        public string UserId { get; set; }
        public string SeatNo { get; set; }
        public DateTime InvoiceDate { get; set; }
        public int PickLocationId1 { get; set; }
        public int PickLocationId2 { get; set; }
        public int RouteId { get; set; }
		public float TotalMoney { get; set; }
        public int Status { get; set; }

        public Ticket()
        {
            UserId = string.Empty;
            SeatNo = string.Empty;
            InvoiceDate = DateTime.MinValue;
            PickLocationId1 = 0;
            PickLocationId2 = 0;
            RouteId = 0;
            TotalMoney = 0;
            Status = 0;
        }
        public Ticket(string userid, string seatno, int pick1, int pick2, int routeid, float total, int status)
		{
			UserId = userid;
			SeatNo = seatno;
			PickLocationId1 = pick1;
			PickLocationId2 = pick2;
			RouteId = routeid;
			TotalMoney = total;
            Status = status;
        }
        public virtual PickLocation PickLocationId1Navigation { get; set; }
        public virtual PickLocation PickLocationId2Navigation { get; set; }
        public virtual Route Route { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

FastGuard/Controllers/TicketsController.cs
using FastGuard.Data;
using FastGuard.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Reflection.Metadata;

namespace FastGuard.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public TicketsController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [Authorize(Roles = "Admin, Employee, Customer")]
        public async Task<IActionResult> SearchTicket()
        {
            return _context.Locations != null ?
                          View(await _context.Locations.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Locations'  is null.");
        }
        [Authorize(Roles = "Admin, Employee, Customer")]
        public async Task<IActionResult> BookedTicket(string searchbarinput = "")
        {
            updateTicketStatus();

            DateTime parsedDate;
            bool isDate = DateTime.TryParse(searchbarinput, out parsedDate);
            TimeSpan parsedTime;
            bool isTime = TimeSpan.TryParseExact(searchbarinput, "HH\\:mm", CultureInfo.InvariantCulture, out parsedTime);
            var user = await _userManager.GetUserAsync(User);

            List<Ticket> bookedTickets = new List<Ticket>();

            if (await _userManager.IsInRoleAsync(user, "Customer"))
            {
                // Lấy danh sách vé đã đặt của khách hàng
                if(searchbarinput != null)
                    bookedTickets = await _context.Tickets
                        .Where(t => t.UserId == user.Id)
                        .Include(p => p.PickLocationId1Navigation)
                        .Include(p => p.Route)
                        .Include(p => p.PickLocationId2Navigation)
                        .Where(r => r.User.Name.Contains(searchbarinput)
                        || r.SeatNo.Contains(searchbarinput)
                        || r.PickLocationId1Navigation.PickLocationName.Contains(searchbarinput)
                        || r.PickLocationId2Navigation.PickLocationName.Contains(searchbarinput)
                        || r.TotalMoney.ToString().Contains(searchbarinput)
                        || (DateTime.TryParseExact(searchbarinput, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out parsedDate)
                            && r.InvoiceDate.Date == parsedDate.Date)
                        || (DateTime.TryParseExact(searchbarinput, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out parsedDate)
                            && r.Route.StartDate == parsedDate.Date)
                        || (r.Route.StartDate.TimeOfDay == parsedTime))
                        .ToListAsync();
                else
					bookedTickets = await _context.Tickets
						.Where(t => t.UserId == user.Id)
						.Include(p => p.PickLocationId1Navigation)
						.Include(p => p.Route)
						.Include(p => p.PickLocationId2Navigation)
						.ToListAsync();
			}
            else if (await _userManager.IsInRoleAsync(user, "Admin") || await _userManager.IsInRoleAsync(user, "Employee"))
            {
				// Lấy tất cả danh sách vé cho admin
				if (searchbarinput != null)
					bookedTickets = await _context.Tickets.Include(p => p.User)
                        .Include(p => p.Route)
                        .Include(p => p.PickLocationId1Navigation)
                        .Include(p => p.PickLocationId2Navigation)
                        .Where(r => r.User.Name.Contains(searchbarinput)
                        || r.SeatNo.Contains(searchbarinput)
                        || r.PickLocationId1Navigation.PickLocationName.Contains(searchbarinput)
                        || r.PickLocationId2Navigation.PickLocationName.Contains(searchbarinput)
                        || r.TotalMoney.ToString().Contains(searchbarinput)
                        || r.InvoiceDate.ToString().Contains(searchbarinput)
                        || r.Route.StartDate.ToString().Contains(searchbarinput)
                        || (DateTime.TryParseExact(searchbarinput, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out parsedDate)
                            && r.InvoiceDate.Date == parsedDate.Date)
                        || (DateTime.TryParseExact(searchbarinput, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out parsedDate)
                            && r.Route.StartDate.Date == parsedDate.Date)
                        || (r.Route.StartDate.TimeOfDay == parsedTime))
                        .ToListAsync();
                else
					bookedTickets = await _context.Tickets.Include(p => p.User)
						.Include(p => p.Route)
						.Include(p => p.PickLocationId1Navigation)
						.Include(p => p.PickLocationId2Navigation)
						.ToListAsync();
			}

            return View(bookedTickets);
        }

        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            var route = await _context.Routes.FindAsync(ticket.RouteId);

            if (ticket == null)
            {
                return NotFound();
            }
            var seatNos = _context.Seats
                .Where(s => !_context.Tickets
                    .Where(t => t.RouteId == ticket.RouteId)
                    .Any(t => t.SeatNo == s.SeatNo));

            ViewData["SeatNo"] = new SelectList(seatNos, "SeatNo", "SeatNo");

            var pickLocation1 = _context.PickLocations
                .Where(s => s.LocationId == route.LocationId1)
                .ToList();
            ViewData["PickLocationName1"] = new SelectList(pickLocation1, "PickLocationId", "PickLocationName");

            var pickLocation2 = _context.PickLocations
                .Where(s => s.LocationId == route.LocationId2)
                .ToList();
            ViewData["PickLocationName2"] = new SelectList(pickLocation2, "PickLocationId", "PickLocationName");

            return View(ticket);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InvoiceId,UserId,SeatNo,InvoiceDate,PickLocationId1,PickLocationId2,RouteId,TotalMoney")] Ticket ticket)
        {
            if (id != ticket.InvoiceId)
            {
                return NotFound();
            }

            try
            {
                _context.Update(ticket);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TicketExists(ticket.InvoiceId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            var route = await _context.Routes.FindAsync(ticket.RouteId);
            var seatNos = _context.Seats
                .Where(s => !_context.Tickets
                    .Where(t => t.RouteId == ticket.RouteId)
                    .Any(t => t.SeatNo == s.SeatNo));

            ViewData["SeatNo"] = new SelectList(seatNos, "SeatNo", "SeatNo");

            var pickLocation1 = _context.PickLocations
                .Where(s => s.LocationId == route.LocationId1)
                .ToList();
            ViewData["PickLocationName1"] = new SelectList(pickLocation1, "PickLocationId", "PickLocationName");

            var pickLocation2 = _context.PickLocations
                .Where(s => s.LocationId == route.LocationId2)
                .ToList();
            ViewData["PickLocationName2"] = new SelectList(pickLocation2, "PickLocationId", "PickLocationName");

            return View(ticket);
        }

        [Authorize(Roles = "Admin, Employee, Customer")]
        [HttpGet]
        public IActionResult Tickets(string start, int startid, string end, int endid, DateTime startdate)
        {
            string strStartDate = startdate.ToString("yyyy-MM-dd");
            ViewData["route"] = start + " - " + end;
            ApplicationDbContext context = HttpContext.RequestServices.GetService(typeof(FastGuard.Data.ApplicationDbContext)) as ApplicationDbContext;
            List<Models.Route> list = context.SearchRoute(startid, endid, strStartDate);
			List<Dictionary<string, object>> routes = context.CountBookedSeat(startid, endid, strStartDate);
			ViewData["routes"] = routes;

			return View(list);
        }

        [Authorize(Roles = "Admin, Employee, Customer")]
        public async Task<IActionResult> Checkout(int routeid, string start, string end)
        {
            ViewData["start"] = start;
            ViewData["end"] = end;
            //lay pick location 1
            var query = from a in _context.Routes
                        join b in _context.Locations on a.LocationId1 equals b.LocationId
                        join c in _context.PickLocations on b.LocationId equals c.LocationId
                        where a.RouteId == routeid
                        select new { Route = a, Location = b, PickLocation = c };

            var picklocations1 = query.ToList();
            ViewData["PickLocationId1"] = new SelectList(picklocations1, "PickLocation.PickLocationId", "PickLocation.PickLocationName");
            //lay pick location 2
            query = from a in _context.Routes

FastGuard/Views/Tickets/BookedTicket.cshtml
@model IEnumerable<Ticket>
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> signInManager;

<div class="container mt-4">    
    <h1>Vé đã đặt</h1>
    <div class="d-flex gap-3 mb-3">
        <form asp-action="BookedTicket" method="get">
            <div style="width: 400px; display:flex;">
                <input type="search" id="searchbarinput" name="searchbarinput" class="form-control" placeholder="Nhập nội dung tìm kiếm" />
                <button type="submit" class="btn btn-primary" data-mdb-ripple-init>
                    <i class="fas fa-search"></i>
                </button>
                <a asp-action="BookedTicket" type="submit" class="btn btn-dark mx-3" data-mdb-ripple-init>
                    <i class="fa-solid fa-arrows-rotate"></i>
                </a>
            </div>
        </form>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Tên người đặt</th>
                <th>Số ghế</th>
                <th>Ngày đặt</th>
                <th>Thời gian khởi hành</th>
                <th>Điểm đón</th>
                <th>Điểm trả</th>
                <th>Giá vé</th>
                <th>Trạng thái</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.User.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.SeatNo)</td>
                    <td>@item.InvoiceDate.ToString("dd/MM/yyyy")</td>
                    <td>@item.Route.StartDate.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>@Html.DisplayFor(modelItem => item.PickLocationId1Navigation.PickLocationName)</td>
                    <td>@Html.DisplayFor(modelItem => item.PickLocationId2Navigation.PickLocationName)</td>
                    <td>@Html.DisplayFor(modelItem => item.TotalMoney)</td>
                    @if(item.Status == 0)
                    {
                        <td style="color: green">Chưa khởi hành</td>
                    }
                    else
                    {
                        <td style="color: gray">Đã khởi hành</td>
                    }
                    <td>
                        <div class="d-flex gap-2" role="group">
                            @if (item.Status == 0)
                            {
                                <a asp-action="Delete" asp-route-id="@item.InvoiceId" class="btn btn-danger">
                                    <i class="fas fa-trash"></i> Hủy vé
                                </a>
                            }
                            
                            @if (signInManager.IsSignedIn(User) && ((User.IsInRole("Admin")) || (User.IsInRole("Employee"))))
                            {
                                <a asp-action="Edit" asp-route-id="@item.InvoiceId" class="btn btn-primary">
                                    <i class="fas fa-edit"></i> Sửa
                                </a>
                            }
                            <a asp-action="Details" asp-route-id="@item.InvoiceId" class="btn btn-secondary">
                                <i class="fas fa-info-circle"></i> Chi tiết vé
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

FastGuard/Views/Tickets/Delete.cshtml
@model FastGuard.Models.Ticket


<div class="container mt-4">
    @if (Model.Status == 1)
    {
        <h1 style="color: red;">Chuyến đi này không thể hủy vì nó đã khởi hành</h1>
    }
    else
    {
        <h1>Hủy vé</h1>
        <h3>Bạn có muốn hủy vé này không?</h3>
        <div>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    Người đặt
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.User.Name)
                </dd>
                <dt class="col-sm-2">
                    Số ghế
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.SeatNo)
                </dd>
                <dt class="col-sm-2">
                    Ngày mua
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.InvoiceDate)
                </dd>
                <dt class="col-sm-2">
                    Điểm đón
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.PickLocationId1Navigation.PickLocationName)
                </dd>
                <dt class="col-sm-2">
                    Điểm trả
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.PickLocationId2Navigation.PickLocationName)
                </dd>
                <dt class="col-sm-2">
                    Chuyến
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Route.RouteId)
                </dd>
                <dt class="col-sm-2">
                    Giá vé
                </dt>
                <dd class="col-sm-10 fw-bold" style="color: #8e2de2;">
                    @Html.DisplayFor(model => model.TotalMoney)
                </dd>
                <dt class="col-sm-2">
                    Trạng thái
                </dt>
                <dd class="col-sm-10 fw-bold" style="color: #8e2de2;">

                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="InvoiceId" />
                <input type="submit" value="Hủy" class="btn btn-danger" />
                <a asp-action="BookedTicket" class="btn btn-info">Trở Về</a>
            </form>
        </div>
    }
    
</div>

FastGuard/Views/Tickets/Details.cshtml
@model FastGuard.Models.Ticket
@{
	string start = ViewData["start"].ToString();
	string end = ViewData["end"].ToString();
	string route = start + " - " + end;
}

<style>
	.label-bold {
		font-size: 20px;
		font-weight: bold;
	}

	.customer-info, .ticket-info {
		border: 1px solid #d9d9d9;
		border-radius: 10px;
		padding: 10px 10px;
	}

	input {
		height: 45px;
		padding: 0 5px;
		border-radius: 7px;
		width: 400px;
		border: 1px solid #8e2de2;
		background: #f2f2f2;
		color: black;
	}

		input:focus {
			outline: 2px solid #8e2de2;
		}
</style>

<div class="container mt-4">
	<h1>Chi tiết vé</h1>
	<div>
		<hr />
		<div class="d-flex gap-3">
			<div class="ticket-info">
				<div class="label-bold">Thông tin chuyến đi</div>
				<div>Tuyến</div>
				<input type="text" value="@route" name="cusname" disabled />
				<div>Điểm đón</div>
				<input type="text" value="@Model.PickLocationId1Navigation.PickLocationName" name="cusname" disabled />
				<div>Điểm trả</div>
				<input type="text" value="@Model.PickLocationId2Navigation.PickLocationName" name="cusname" disabled />
				<div>Thời gian khởi hành</div>
				<input type="text" value="@Model.Route.StartDate.ToString("dd/MM/yyyy HH:mm")" name="cusname" disabled />
				<div>Số ghế</div>
				<input type="text" value="@Model.SeatNo" name="cusname" disabled />
				<div>Giá vé</div>
			</div>
			<div class="customer-info">
				<div class="label-bold">Thông tin khách hàng</div>
				<div>Họ và tên</div>
				<input type="text" value="@Model.User.Name" disabled />
				<div>Số điện thoại</div>
				<input type="text" value="@Model.User.PhoneNumber" disabled>
				<div>Email</div>
				<input type="text" value="@Model.User.Email" disabled />
			</div>
		</div>
	</div>
	<div class="mt-3">
		<a asp-action="BookedTicket" class="btn btn-info">Trở Về</a>
	</div>
</div>

FastGuard/Views/Tickets/Edit.cshtml
@model FastGuard.Models.Ticket

<div class="container mt-4">
    <h1>Thay đổi thông tin vé</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="InvoiceId" />
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" readonly />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SeatNo" class="control-label">Số ghế</label>
                    <select asp-for="SeatNo" class="form-control" asp-items="ViewBag.SeatNo"></select>
                    <span asp-validation-for="SeatNo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PickLocationId1" class="control-label">Điểm đón</label>
                    <select asp-for="PickLocationId1" class="form-control" asp-items="ViewBag.PickLocationName1"></select>
                    <span asp-validation-for="PickLocationId1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PickLocationId2" class="control-label">Điểm trả</label>
                    <select asp-for="PickLocationId2" class="form-control" asp-items="ViewBag.PickLocationName2"></select>
                    <span asp-validation-for="PickLocationId2" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="RouteId" type="hidden" />
                </div>
                <div class="form-group">
                    <input asp-for="TotalMoney" type="hidden" />
                </div>
                <div class="form-group mt-3 gap-3">
                    <input type="submit" value="Lưu" class="btn btn-primary" />
                    <a asp-action="BookedTicket" class="btn btn-info">Trở Về</a>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FastGuard/Views/Tickets/PayResult.cshtml
@{

}
<style>
	.custom-button {
		background: linear-gradient(90deg, rgba(142,45,226,1) 32%, rgba(74,0,224,1) 100%);
		font-size: 21px;
		border-radius: 25px;
		text-align: center;
		border: 1px solid transparent;
		color: white;
		text-decoration: none;
		padding: 7px 40px;
	}

		.custom-button:hover {
			background: #9e4be7;
			color: white;
		}
</style>
<div class="d-flex flex-column gap-3 justify-content-center text-center w-100 h-75 py-5 fs-5">
	<i class="fa-solid fa-circle-check fa-beat" style="font-size: 50px;"></i>
	<h5>@ViewData["message"]!</h5>
	<div>
		<a asp-area="" asp-controller="Tickets" asp-action="SearchTicket" class="custom-button">Đặt vé khác</a>
		<a asp-area="" asp-controller="Tickets" asp-action="BookedTicket" class="custom-button">Xem vé đã đặt</a>
	</div>
	
</div>

FastGuard/Views/Tickets/Tickets.cshtml
@model IEnumerable<Route>

@{
	ViewData["Title"] = "Chọn chuyến thích hợp";
	List<Dictionary<string, object>> routes = ViewData["routes"] as List<Dictionary<string, object>>;
}
<style>
	.start-date {
		display: flex;
		justify-content: space-between;
	}

	.notfound {
		display: flex;
		flex-direction: column;
		gap: 10px;
		justify-content: center;
		align-items: center;
		width: 100%;
		height: 90vh;
	}

	.start-date-icon {
		display: flex;
		justify-content: center;
		align-items: center;
		width: 80%;
		gap: 10px;
	}

		.start-date-icon hr {
			width: 80%;
			color: black;
			/* border: 1px dashed black; */
		}

	.card-price {
		display: flex;
		justify-content: space-between;
	}

	.text-violet {
		color: #4a00e0;
		font-weight: bold;
		font-size: 18px;
		display: flex;
		gap: 10px;
		align-items: center;
	}

	.text-grayy-icon {
		color: #8c8c8c;
		font-size: 8px;
	}

	.text-grayy {
		color: #8c8c8c;
	}
</style>
@if (Model.Count() != 0)
{
	<h1>@ViewData["Title"]</h1>
}

@* <h3 id="searchResult">@ViewData["route"] (@Model.Count())</h3> *@
<h3 id="searchResult"></h3>

@if (Model.Count() == 0)
{
	<div class="notfound">
		<i class="fas fa-exclamation-circle fs-2"></i>
		<h5>Không tìm thấy chuyến thích hợp</h5>
	</div>

}
else
{
	@foreach (var item in Model)
	{
		<div class="card text-center px-2 my-3">
			<div class="card-body">
				<div class="start-date">
					<div>@item.StartDate.ToString("HH:mm")</div>
					<div class="start-date-icon">
						<i class="fa-solid fa-circle"></i>
						<hr>
						<i class="fa-solid fa-location-dot"></i>
					</div>
					<div>@item.EndDate.ToString("HH:mm")</div>
				</div>
			</div>
			<div class="card-footer text-muted">
				<div class="card-price">
					<div class="text-violet">
						<div>@item.Price đ</div>
						<div class="text-grayy-icon">
							<i class="fa-solid fa-circle"></i>
						</div>
						<div class="text-grayy">Giường</div>
						<div class="text-grayy-icon">
							<i class="fa-solid fa-circle"></i>
						</div>
						@foreach(var route in routes)
						{
							if ((int)route["RouteId"] == item.RouteId)
							{
								Convert.ToInt32(route["SLCL"]);
								<div class="text-violet">@(42 - (int)route["SLCL"]) chỗ trống</div>
								break;
							}							
						}
					</div>
					<form action="/Tickets/Checkout" method="get">
						<input type="text" style="display: none;" name="routeid" value="@item.RouteId" />
						<input type="text" style="display: none;" name="start" id="startget" />
						<input type="text" style="display: none;" name="end" id="endget" />
						<button class="btn btn-primary"
								style="background-color: #4a00e0"
								type="submit">
							Chọn chuyến
						</button>
					</form>
				</div>
			</div>
		</div>
	}
}
<script>
	// Lấy giá trị của tham số từ URL
	function getURLParameter(name) {
		name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
		var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
		var results = regex.exec(window.location.href);
		return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
	}

	var start = getURLParameter('start');
	var end = getURLParameter('end');

	document.querySelector('#startget').value = start;
	document.querySelector('#endget').value = end;
	document.querySelector('#searchResult').innerText = start + " - " + end + " (" + @Model.Count() + ")";

</script>