FastGuard/Controllers/CoachesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FastGuard.Data;
using FastGuard.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace FastGuard.Controllers
{
	[Authorize(Roles = "Admin, Employee")]
	public class CoachesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CoachesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Coaches
        public async Task<IActionResult> Index(string searchbarinput = "")
        {
            var applicationDbContext = _context.Coaches.Include(c => c.User);

            var coaches = applicationDbContext
				.Where(c => c.CoachNo.Contains(searchbarinput)
                || c.Supplier.Contains(searchbarinput)
                || c.Capacity.ToString().Contains(searchbarinput)
                || c.User.Name.Contains(searchbarinput));

            if(searchbarinput == null)
                return View(await applicationDbContext.ToListAsync());
            else
                return View(coaches);
        }

        // GET: Coaches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Coaches == null)
            {
                return NotFound();
            }

            var coach = await _context.Coaches
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CoachId == id);
            if (coach == null)
            {
                return NotFound();
            }

            return View(coach);
        }

        // GET: Coaches/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id");
            ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName");
            ViewData["ErrorCoach"] = "";
            return View();
            //ViewData["UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id");
            //int count;
            //ApplicationDbContext context = HttpContext.RequestServices.GetService(typeof(FastGuard.Data.ApplicationDbContext)) as ApplicationDbContext;
            //count = context.CreateCoach(c);
            //if (count > 0)
            //    ViewData["thongbao"] = "Insert thành công";
            //else
            //    ViewData["thongbao"] = "Insert không thành công";
            //return View();
        }

        // POST: Coaches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CoachId,CoachNo,UserId,Supplier,Capacity,Status,Description")] Coach coach)
        {
            //if (ModelState.IsValid)
            //{
            //    _context.Add(coach);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["UserId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", coach.UserId);
            //return View(coach);
            ViewData["ErrorCoach"] = "";
            var checkCoach = await _context.Coaches
              .FirstOrDefaultAsync(m => m.CoachNo == coach.CoachNo);
            if(checkCoach!=null)
            {
                ViewData["ErrorCoach"] = "Không thể thêm xe, biển số xe đã bị trùng";
                return View("Create");
            }
            _context.Add(coach);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Coaches/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.Coaches == null)
            {
                return NotFound();
            }

            var coach = await _context.Coaches.FindAsync(id);
            if (coach == null)
            {
                return NotFound();
            }
            var drivers = await _userManager.GetUsersInRoleAsync("Driver");

            ViewData["UserId"] = new SelectList(drivers, "Id", "Id", coach.UserId);
            return View(coach);
        }

        // POST: Coaches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CoachId,CoachNo,UserId,Supplier,Capacity,Status,Description")] Coach coach)
        {
            if (id != coach.CoachId)
            {
                return NotFound();
            }

            if (true)
            {
                try
                {
                    _context.Update(coach);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoachExists(coach.CoachId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                var drivers = await _userManager.GetUsersInRoleAsync("Driver");
                ViewData["UserId"] = new SelectList(drivers, "Id", "Id", coach.UserId);

                return RedirectToAction(nameof(Index));
            }
            
            return View(coach);
        }

        // GET: Coaches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Coaches == null)
            {
                return NotFound();
            }

            var coach = await _context.Coaches
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CoachId == id);
            if (coach == null)
            {
                return NotFound();
            }

            return View(coach);
        }

        // POST: Coaches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Coaches == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Coaches'  is null.");
            }
            var coach = await _context.Coaches.FindAsync(id);
            if (coach != null)
            {
                _context.Coaches.Remove(coach);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoachExists(int id)
        {
          return (_context.Coaches?.Any(e => e.CoachId == id)).GetValueOrDefault();
        }
    }
}

FastGuard/Controllers/RoutesController.cs
using FastGuard.Data;
using FastGuard.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace FastGuard.Controllers
{
	[Authorize(Roles = "Admin, Employee")]
	public class RoutesController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;
		private readonly IConfiguration _configuration;

		public RoutesController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, IConfiguration configuration, ApplicationDbContext context)
		{
			_userManager = userManager;
			_roleManager = roleManager;
			_configuration = configuration;
			_context = context;
		}

		// GET: Routes
		public async Task<IActionResult> Index(string searchbarinput = "")
		{
			DateTime parsedDate;
			bool isDate = DateTime.TryParse(searchbarinput, out parsedDate);
            TimeSpan parsedTime;
            bool isTime = TimeSpan.TryParseExact(searchbarinput, "HH\\:mm", CultureInfo.InvariantCulture, out parsedTime);

			var applicationDbContext = _context.Routes.Include(r => r.Coach)
				.Include(r => r.LocationId1Navigation)
				.Include(r => r.LocationId2Navigation);
			var routes = applicationDbContext
				.Where(r => r.LocationId2Navigation.LocationName.Contains(searchbarinput)
					|| r.LocationId1Navigation.LocationName.Contains(searchbarinput)
					|| r.Coach.CoachNo.Contains(searchbarinput)
					|| r.Price.ToString().Contains(searchbarinput)
                    || r.StartDate.ToString().Contains(searchbarinput)
                    || r.EndDate.ToString().Contains(searchbarinput)
                    || (r.StartDate.TimeOfDay == parsedTime)
                    || (r.EndDate.TimeOfDay == parsedTime)
                    || (DateTime.TryParseExact(searchbarinput, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out parsedDate)
						&& r.StartDate.Date == parsedDate.Date)
					|| (DateTime.TryParseExact(searchbarinput, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out parsedDate)
						&& r.EndDate.Date == parsedDate.Date));

			if(searchbarinput == null)
				return View(await applicationDbContext.ToListAsync());
			else
				return View(routes);
		}
		// GET: Routes/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Routes == null)
			{
				return NotFound();
			}

			var route = await _context.Routes
				.Include(r => r.Coach)
				.Include(r => r.LocationId1Navigation)
				.Include(r => r.LocationId2Navigation)
				.FirstOrDefaultAsync(m => m.RouteId == id);
			if (route == null)
			{
				return NotFound();
			}

			return View(route);
		}

		// GET: Routes/Create
		public IActionResult Create()
		{
			ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo");
			ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName");
			ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName");
			return View();
		}

		// POST: Routes/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		// POST: Routes/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind(",CoachId,LocationId1,LocationId2,StartDate,EndDate,Price")] Models.Route route)
		{
			if (ModelState.IsValid)
			{

				bool routeExists = await _context.Routes.AnyAsync(r =>
					r.CoachId == route.CoachId &&
					r.LocationId1 == route.LocationId1 &&
					r.LocationId2 == route.LocationId2 &&
					r.StartDate == route.StartDate &&
					r.EndDate == route.EndDate &&
					r.Price == route.Price);

				if (routeExists)
				{
					ModelState.AddModelError("", "The route already exists.");
					ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
					ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
					ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);
					return View(route);
				}
				var route1 = await _context.Routes.FirstOrDefaultAsync(t => t.CoachId == route.CoachId && t.StartDate.Date == route.StartDate.Date);
				if (route1 != null)
				{
					ModelState.AddModelError("", "Xe đang chọn đã phụ trách chuyến khác");
					ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
					ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
					ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);
					return View(route);
				}
				if (route.EndDate < route.StartDate)
				{
					ModelState.AddModelError("", "Ngày đến không được sớm hơn ngày khởi hành");
					ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
					ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
					ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);
					return View(route);
				}
				if (route.LocationId1 == route.LocationId2)
				{
					ModelState.AddModelError("", "Điểm đón không được trùng với điểm đi");
					ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
					ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
					ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);
					return View(route);
				}
				if (route.StartDate.ToString("dd/MM/yyyy") == route.EndDate.ToString("dd/MM/yyyy"))
				{
					ModelState.AddModelError("", "Ngày khởi hành không được trùng với ngày đi");
					ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
					ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
					ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);
					return View(route);
				}
				_context.Add(route);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			ViewData["CoachId"] = new SelectList(_context.Coaches, "CoachId", "CoachId", route.CoachId);
			ViewData["LocationId1"] = new SelectList(_context.Locations, "LocationId", "LocationId", route.LocationId1);
			ViewData["LocationId2"] = new SelectList(_context.Locations, "LocationId", "LocationId", route.LocationId2);
			return View(route);
		}

		// GET: Routes/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Routes == null)
			{
				return NotFound();
			}

			var route = await _context.Routes.FindAsync(id);
			if (route == null)
			{
				return NotFound();
			}

			ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
			ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
			ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);

			return View(route);
		}

		// POST: Routes/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("RouteId,CoachId,LocationId1,LocationId2,StartDate,EndDate,Price")] Models.Route route)
		{
			if (id != route.RouteId)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					var route1 = await _context.Routes.FirstOrDefaultAsync(t => t.CoachId == route.CoachId && t.StartDate.Date == route.StartDate.Date && t.RouteId != route.RouteId);
					if (route1 != null)
					{
						ModelState.AddModelError("", "Xe đang chọn đã phụ trách chuyến khác");
						ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
						ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
						ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);
						return View(route);
					}
					if (route.EndDate < route.StartDate)
					{
						ModelState.AddModelError("", "Ngày đến không được sớm hơn ngày khởi hành");
						ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
						ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
						ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);
						return View(route);
					}
					if (route.LocationId1 == route.LocationId2)
					{
						ModelState.AddModelError("", "Điểm đón không được trùng với điểm đi");
						ViewData["CoachNo"] = new SelectList(_context.Coaches, "CoachId", "CoachNo", route.CoachId);
						ViewData["LocationName1"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId1);
						ViewData["LocationName2"] = new SelectList(_context.Locations, "LocationId", "LocationName", route.LocationId2);
						return View(route);
					}
					if (route.StartDate.ToString("dd/MM/yyyy") == route.EndDate.ToString("dd/MM/yyyy"))
					{

FastGuard/Views/Home/Index.cshtml
@model List<object>;
@{
	ViewData["Title"] = "Home Page";
	// var list = ViewData["Dem"]; // 0- nhan vien, 1- khach hang,2-tai xe,3-xe,4-pick location,5-dia diem(location),6-so tuyen(route),7-so ve
}
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
<!-- iCheck -->
<link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
<!-- JQVMap -->
<link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
<!-- Theme style file nay lam loi font -->
@* <link rel="stylesheet" href="~/dist/css/adminlte.min.css"> *@
<!-- overlayScrollbars -->
<link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
<!-- Daterange picker -->
<link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
<!-- summernote -->
<link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">

<style>
	.home {
		margin: 0 auto;
		padding: 10px 20px;
	}

	.custom-card {
		display: flex;
		flex-direction: column;
		width: 20%;
		heigh: 10%;
		color: white;
		border-radius: 8px;
		border-color: transparent;
	}

		.custom-card .above i {
			font-size: 60px;
		}

		.custom-card .above {
			display: flex;
			justify-content: space-between;
			padding: 10px 15px;
			align-items: center;
		}

		.custom-card .above p{
			font-weight: bold;
			font-size: 25px;
		}

		.custom-card .beneath {
			display: flex;
			padding: 10px 15px;
			align-items: center;
			justify-content: center;
			text-decoration: none;
			gap: 5px;
		}

			.custom-card .beneath i {
				padding-top: 2px;
			}

		.custom-card .beneath a{
			color: white;
			text-decoration: none;			
		}

			.custom-card .beneath a:hover {
				text-decoration: underline;
			}

	.card-content {
		display: flex;
		flex-direction: column;
	}
</style>


<br />

<div class="home">
	<!-- Small boxes (Stat box) -->
	<div class="d-flex flex-column gap-3 w-100 mb-3">
		<div class="d-flex gap-3 justify-content-center">
			<div class="custom-card" style="background-color: #4158D0;
			background-image: linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%);
			">
				<div class="above">
					<div class="card-content">
						<h3> @ViewData["KhachHang"].ToString()</h3>
						<p>Khách hàng</p>
					</div>
					<i class="fa-solid fa-user"></i>
				</div>
				<div class="beneath">
					<a asp-area="" asp-controller="Customers" asp-action="Index" class="small-box-footer">
						More Infor
					</a>
					<i class="fas fa-arrow-circle-right"></i>
				</div>				
			</div>
			<div class="custom-card" style="background-color: #0093E9;
				background-image: linear-gradient(160deg, #0093E9 0%, #80D0C7 100%);
			">
				<div class="above">
					<div class="card-content">
						<h3>  @ViewData["NhanVien"].ToString() </h3>
						<p>
							Nhân viên
						</p>
					</div>
					<i class="fa-solid fa-user-tie"></i>
				</div>
				<div class="beneath">
					<a asp-area="" asp-controller="Employee" asp-action="Index" class="small-box-footer">
						More Infor
					</a>
					<i class="fas fa-arrow-circle-right"></i>
				</div>
			</div>
			<div class="custom-card" style="background-color: #FFE53B;
				background-image: linear-gradient(147deg, #FFE53B 0%, #FF2525 74%);
				">
				<div class="above">
					<div class="card-content">
						<h3> @ViewData["TaiXe"].ToString() </h3>
						<p>Tài xế</p>
					</div>
					<i class="fa-solid fa-road"></i>
				</div>
				<div class="beneath">
					<a asp-area="" asp-controller="Driver" asp-action="Index" class="small-box-footer">
						More Infor
					</a>
					<i class="fas fa-arrow-circle-right"></i>
				</div>
			</div>
			<div class="custom-card" style="background-color: #08AEEA;
				background-image: linear-gradient(0deg, #08AEEA 0%, #2AF598 100%);
			">
				<div class="above">
					<div class="card-content">
						<h3> @ViewData["Xe"].ToString()</h3>
						<p>Xe</p>
					</div>
					<i class="fa-solid fa-van-shuttle"></i>
				</div>
				<div class="beneath">
					<a asp-area="" asp-controller="Coaches" asp-action="Index" class="small-box-footer">
						More Infor
					</a>
					<i class="fas fa-arrow-circle-right"></i>
				</div>
			</div>
		</div>
		<div class="d-flex gap-3 justify-content-center">
			<div class="custom-card" style="background-color: #3EECAC;
				background-image: linear-gradient(19deg, #3EECAC 0%, #EE74E1 100%);
			">
				<div class="above">
					<div class="card-content">
						<h3> @ViewData["DiaDiem"].ToString()</h3>
						<p>Địa điểm</p>
					</div>
					<i class="fa-solid fa-map-location-dot"></i>
				</div>
				<div class="beneath">
					<a asp-area="" asp-controller="Locations" asp-action="Index" class="small-box-footer">
						More Infor 
					</a>
					<i class="fas fa-arrow-circle-right"></i>
				</div>
			</div>
			<div class="custom-card" style="background-color: #FF9A8B;
				background-image: linear-gradient(90deg, #FF9A8B 0%, #FF6A88 55%, #FF99AC 100%);
			">
				<div class="above">
					<div class="card-content">
						<h3>@ViewData["DiemDon"].ToString()</h3>
						<p>Điểm đón   </p>
					</div>
					<i class="fa-solid fa-location-dot"></i>
				</div>
				<div class="beneath">
					<a asp-area="" asp-controller="PickLocations" asp-action="Index" class="small-box-footer">
						More Infor
					</a>
					<i class="fas fa-arrow-circle-right"></i>
				</div>
			</div>
			<div class="custom-card" style="background-color: #FF3CAC;
				background-image: linear-gradient(225deg, #FF3CAC 0%, #784BA0 50%, #2B86C5 100%);
			">
				<div class="above">
					<div class="card-content">
						<h3> @ViewData["SoTuyen"].ToString()</h3>
						<p>Tuyến xe</p>
					</div>
					<i class="fa-solid fa-route"></i>
				</div>
				<div class="beneath">
					<a asp-area="" asp-controller="Routes" asp-action="Index" class="small-box-footer">
						More Infor 
					</a>
					<i class="fas fa-arrow-circle-right"></i>
				</div>
			</div>	
			<div class="custom-card" style="background-color: #F4D03F;
				background-image: linear-gradient(132deg, #F4D03F 0%, #16A085 100%);
			">
				<div class="above">
					<div class="card-content">
						<h3>@ViewData["VeXe"].ToString()</h3>
						<p>Đặt vé xe</p>
					</div>
					<i class="fa fa-ticket"></i>
				</div>
				<div class="beneath">
					<a asp-area="" asp-controller="Tickets" asp-action="SearchTicket" class="small-box-footer">
						More Infor
					</a>
					<i class="fas fa-arrow-circle-right"></i>
				</div>
			</div>
		</div>
	</div>	

	<div class="card card-info">
		<div class="card-header" style="background: linear-gradient(90deg, #8e2de2, #4a00e0); color: #ffffff;">
			<h3 class="card-title">Biểu đồ danh thu</h3>
			<div class="card-tools">
				<button type="button" class="btn btn-tool" data-card-widget="collapse">
					<i class="fas fa-minus"></i>
				</button>
			</div>
		</div>
		<div class="card-body">
			<div>
				<label for="year-select">Chọn năm:</label>
				<select id="year-select"></select>
			</div>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
			<script>
				$(document).ready(function () {
					var yearOptions = '';
					for (var year = 2021; year <= 2023; year++) {
						if (year == 2023)
							yearOptions += '<option selected value="' + year + '">' + year + '</option  >';
						else
							yearOptions += '<option value="' + year + '">' + year + '</option  >';
					}
					$('#year-select').html(yearOptions);
				});
			</script>
			<p id="revenue-text"></p>
			<canvas id="body" style="min-height: 200px; height: 220px; max-height: 200px; max-width: 100%;"></canvas>
		</div>
	</div>
</div>

<!-- jQuery -->
@* <script src="../../plugins/jquery/jquery.min.js"></script> *@
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="../../plugins/chart.js/Chart.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
@* <script src="../../dist/js/demo.js"></script> *@
<!-- Page specific script -->
<script>
	$(function () {
		var revenueData = {
			'2021': new Array(12).fill(0),
			'2022': new Array(12).fill(0),
			'2023': new Array(12).fill(0)
		};

	@foreach (var item in Model)
	{
		var x = (int)@item.GetType().GetProperty("thang").GetValue(@item, null) - 1;
		var doanhThu = (double)@item.GetType().GetProperty("doanhThu").GetValue(@item, null)/1000000;
		var nam = @item.GetType().GetProperty("nam").GetValue(@item, null).ToString();
		if (@nam == "2021")
		{
			@:revenueData['2021'][@x] = @doanhThu;
		}
		else if (@nam == "2022")
		{
			@:revenueData['2022'][@x]= @doanhThu

		}
		else
		{
			@:revenueData['2023'][@x]  =@doanhThu;
		}
	}

		var lineChartCanvas = $('#body').get(0).getContext('2d');
		var lineChartData = {
			labels: ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6', 'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12'],
			datasets: [
				{
					label: 'Doanh thu',
					backgroundColor: 'linear-gradient(90deg, #8e2de2, #4a00e0)',
					borderColor: '#ffffff',
					pointRadius: false,
					pointBackgroundColor: '#8e2de2',
					pointBorderColor: '#4a00e0',
					pointHoverBackgroundColor: '#8e2de2',
					pointHoverBorderColor: '#4a00e0',
					data: revenueData['2023']
				}
			]
		};

		var lineChartOptions = {
			maintainAspectRatio: false,
			responsive: true,
			legend: {
				display: false
			},
			scales: {
				xAxes: [{
					gridLines: {
						display: true, // Hiển thị đường grid trên trục x
					},
					scaleLabel: {
						display: true,
						labelString: 'Tháng' // Tên trục ngang
					}
				}],
				yAxes: [{
					gridLines: {
						display: true, // Hiển thị đường grid trên trục y
					},
					scaleLabel: {
						display: true,
						labelString: 'Doanh thu (triệu đồng)' // Tên trục dọc
					}
				}]
			}
		};

		var lineChart = new Chart(lineChartCanvas, {
			type: 'line',
			data: lineChartData,
			options: lineChartOptions
		});

		$('#year-select').on('change', function () {
			var selectedYear = $(this).val();
			lineChart.data.datasets[0].data = revenueData[selectedYear];
			lineChart.update();
		});
	}
	);
</script>